config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("SocialNetX.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here

    # User Dashboard
    url(r'^dashboard/', include('social_dashboard.urls', namespace="dashboard")),

    # Twitter API
    url(r'^twitter/', include('social_twitter.urls', namespace="twitter")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

social_dashboard/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from .views import social_dashboard, social_dashboard_twitter

urlpatterns = [
    url(r'^$', social_dashboard, name="dashboard_index"),
    url(r'twitter/', social_dashboard_twitter, name="dashboard_twitter"),
]

social_twitter/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from .views import social_twitter_fetch

urlpatterns = [
    url(r'twitter_fetch/', social_twitter_fetch, name="twitter_fetch_latest"),
]

social_dashboard/models.py
from django.db import models

# Create your models here.

social_dashboard/views.py
from django.shortcuts import render, render_to_response

from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

from allauth.socialaccount.models import SocialAccount, SocialToken

from social_twitter.models import Tweet
from django.db.models import Count

# Create your views here.


@login_required
@require_http_methods(['GET'])
def social_dashboard(request):

    return render(request, 'social_dashboard.html')


@login_required
@require_http_methods(['GET'])
def social_dashboard_twitter(request):

    social_twitter_account = SocialAccount.objects.filter(user=request.user, provider='twitter').exists()

    if not social_twitter_account:
        return render(request, 'social_dashboard_twitter_add.html')

    tweets = Tweet.objects.filter(user=request.user).order_by('-created_at')
    score_list = [tweet.score for tweet in tweets]
    #print(score_list)

    count_neg, count_net, count_pos = 0,0,0
    if tweets:
        count_pos = len(tweets.filter(sentiment='positive'))
        count_neg = len(tweets.filter(sentiment='negative'))
        count_net = len(tweets.filter(sentiment='neutral'))


    return render(request, 'social_dashboard_twitter.html', {'tweets': tweets,
                                                             'positive_tweets': count_pos,
                                                             'negative_tweets': count_neg,
                                                             'neutral_tweets': count_net,
                                                             'scores':score_list
                                                              })

social_dashboard/templates/social_dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Welcome to Social Dashboard</h1>
            <a href="{% url 'dashboard:dashboard_twitter'  %}"><button type="button" class="homepage-action-btn btn btn-success"><i class="fa fa-twitter"></i> Twitter</button></a>
        </div>
    </div>
</div>

{% endblock content %}

social_dashboard/templates/social_dashboard_twitter.html
{% extends "base.html" %}

{% block title %}Dashboard Twitter{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Twitter</h1>
            <a href="{% url 'twitter:twitter_fetch_latest' %}"><button type="button" class="homepage-action-btn btn btn-success"><i class="fa fa-twitter"></i> fetch latest tweets</button></a>
                <div class="row">
                    <div class="col-md-6">
                        <div id="chart1" ></div>
                    </div>
                   <div class="col-md-6">
                        <div id="chart2" ></div>
                    </div>
                </div>
            <script>
                var chart1 = c3.generate({
                bindto: '#chart1',
                data: {
                    columns: [
                        ['Positive', {{positive_tweets}}],
                        ['Negative', {{negative_tweets}}],
                        ['Neutral',{{neutral_tweets}}],
                    ],
                    type : 'bar'
                },
                 axis: {
                    x: {
                        label: 'Type'
                    },
                    y: {
                        label: 'Number of tweets'
                    }
                },
                donut: {
                    title: "Sentiment Analysis",

                },
                colors: { Positive:'green', Negative:'red' },
                
            });
                var chart2 = c3.generate({
                bindto: '#chart2',
                data: {
                    columns: [
                        ['Positive', {{positive_tweets}}],
                        ['Negative', {{negative_tweets}}],
                        ['Neutral',{{neutral_tweets}}],
                    ],
                    type : 'donut'
                },
                donut: {
                    title: "Sentiment Analysis",

                },
                colors: { Positive:'green', Negative:'red' },
                
            });

        </script>
        <ul class="list-group">
            {% for tweet in tweets %}

               
                 {% if tweet.sentiment == 'positive' %}
                 <li class="list-group-item" style="font-family: 'Open Sans', sans-serif; font-size:15px; color:green;">{{ tweet.text }}&nbsp&nbsp 
                    <i class="fa fa-thumbs-o-up" aria-hidden="true" style="color:green;"></i>
                </li>
                {% elif tweet.sentiment == 'negative' %}
                    <li class="list-group-item" style="font-family: 'Open Sans', sans-serif; font-size:15px; color:red;">{{ tweet.text }}&nbsp&nbsp 
                    <i class="fa fa-thumbs-o-down" aria-hidden="true" style="color:red;"></i>
                    </li>
                {% elif  tweet.sentiment == 'neutral' %}
                    <li class="list-group-item" style="font-family: 'Open Sans', sans-serif; font-size:15px; color:orange;">{{ tweet.text }}&nbsp&nbsp 
                    <i class="fa fa-hand-stop-o" aria-hidden="true" style="color:yellow;"></i>
                    </li>
                {% else %}
                    <li class="list-group-item" style="font-family: 'Open Sans', sans-serif; font-size:15px; color:orange;">{{ tweet.text }}</li>
                {% endif %}
            {% endfor %}
        </ul>
        </div>
    </div>
</div>

{% endblock content %}

social_dashboard/templates/social_dashboard_twitter_add.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Twitter</h1>
            <p>You have not connected your Twitter account.</p>
            <a href="{% url 'socialaccount_connections' %}"><button type="button" class="homepage-action-btn btn btn-success">Connect <i class="fa fa-twitter"></i></button></a>
        </div>
    </div>
</div>

{% endblock content %}